# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenUTV.UTV
PackageVersion: "2026.10"
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/OpenUTV/utv/releases/download/2026.10/UTV-2026.10-windows-x64.zip
  InstallerSha256: D42A9D5244B5A49257C5FA965EC58CEE6EB5FE6B75F6424E9A75A43E42AB696D
  NestedInstallerFiles:
  - RelativeFilePath: utv-windows-x64\bin\utv.exe
    PortableCommandAlias: utv
Dependencies:
  PackageDependencies:
  - PackageIdentifier: OpenUTV.OpenUTVDeps
    MinimumVersion: "26.5"
ManifestType: installer
ManifestVersion: 1.12.0
